### ISSUE TITLE
Project boxes show top 5 contributors by award amount

### ISSUE THREAD

**Issue by aquabu** [CoMakery/comakery-app#106]
Show project owner first

**Comment by gleenn** [comment]
Do we have design for this?

**Comment by aquabu** [comment]
![screen shot 2016-03-19 at 8 34 13 pm](https://cloud.githubusercontent.com/assets/7595/13902724/0b743d7e-ee12-11e5-9d1a-0c26816a2975.png)

**Comment by gleenn** [comment]
What is a "top contributor"? Top by total coins received or by number of awards? I'm leaning towards coins received...
