### ISSUE TITLE
Browse all page should have public projects in a public projects section

### ISSUE THREAD

**Issue by aquabu** [CoMakery/comakery-app#124]
![screen shot 2016-03-17 at 5 57 36 pm](https://cloud.githubusercontent.com/assets/7595/13865594/26a5b054-ec6a-11e5-8579-5b5931822711.png)

In this case the CoMakery project is listed in the swarmbot instance section.

**Comment by gleenn** [comment]
And specifically, if you are logged in as swarmbot, should only show swarmbot projects in the swarmbot projects section instead of any projects the current account belongs to
