### ISSUE TITLE
Project owner can make a "Community" award

### ISSUE THREAD

**Issue by aquabu** [CoMakery/comakery-app#79]
- [x] "Community" checkbox to the right of the award (can be set by project owner)
- [x] Community members can send community awards on project show page

**Comment by harlantwood** [comment]
bug: I visited noah's project http://staging.comakery.com/projects/5 logged in through a different slack instance than he'd created it in.  but it still allowed me to click the community award and attempt to send it, and then gave me a "forbidden" flash message: `Failed sending award - Not authorized`
