### ISSUE TITLE
User account page shows project coin ownership and ethereum wallet for current slack instance

### ISSUE THREAD

**Issue by aquabu** [CoMakery/comakery-app#87]
For current slack instance:
- [x] Top bar has an account link
- [x] List of awards by project
- [x] Edit current ethereum address with link to etherchain address info e.g. https://www.etherchain.org/account/0x0f7eb552d504296de4099bbcc4461126b23246b5

**[project_name] Awards**

|  Date | Amount | 
| --- | --- |
| Jan... | 150 |
| **Total** | 150 |

**Comment by aquabu** [comment]
![comakery account page](https://cloud.githubusercontent.com/assets/7595/13993481/d361fae2-f0dd-11e5-9a69-43127fc3b299.png)

**Comment by aquabu** [comment]
Checkin with @violasong or @aquabu for latest menu design.

**Comment by aquabu** [comment]
Help message info box should say:
`CoMakery distributes project coins to your private wallet using the Ethereum blockchain. You can download your Ethereum wallet from the [Ethereum](https://www.ethereum.org/) website. Then enter your wallet ID to receive your CoMakery project coins!`

**Comment by gleenn** [comment]
The tooltip was behaving weirdly and not showing up. Might be because there is too much text but I just bailed and took liberties - I always show all the explanatory text and added a call-to-action button to get a wallet. I can fight with the tooltip more but I'm guessing its not worth the time sink. Up to you of course.

**Comment by aquabu** [comment]
Yeah - let's abandon the tool tip. Great work on this. I put a punch list of minor tweaks in #150. I'm marking this one complete.
